In [10]:
import pandas as pd

data = pd.read_csv("C:\\ML\\dataset\\letter-recognition.data")
data.head(10)

T   2   8   3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0  I   5  12   3  7  2   10   5  5  4   13   3    9    2    8    4   10
1  D   4  11   6  8  6   10   6  2  6   10   3    7    3    7    3    9
2  N   7  11   6  6  3    5   9  4  6    4   4   10    6   10    2    8
3  G   2   1   3  1  1    8   6  6  6    6   5    9    1    7    5   10
4  S   4  11   5  8  3    8   8  6  9    5   6    6    0    8    9    7
5  B   4   2   5  4  4    8   7  6  6    7   6    6    2    8    7   10
6  A   1   1   3  2  1    8   2  2  2    8   2    8    1    6    2    7
7  J   2   2   4  4  2   10   6  2  6   12   4    8    1    6    1    7
8  M  11  15  13  9  7   13   2  6  2   12   1    9    8    1    1    8
9  X   3   9   5  7  4    8   7  3  8    5   6    8    2    8    6    7

In [11]:
data.isnull().sum()

T      0
2      0
8      0
3      0
5      0
1      0
8.1    0
13     0
0      0
6      0
6.1    0
10     0
8.2    0
0.1    0
8.3    0
0.2    0
8.4    0
dtype: int64

In [12]:
data.values

array([['I', 5, 12, ..., 8, 4, 10],
       ['D', 4, 11, ..., 7, 3, 9],
       ['N', 7, 11, ..., 10, 2, 8],
       ...,
       ['T', 6, 9, ..., 12, 2, 4],
       ['S', 2, 3, ..., 9, 5, 8],
       ['A', 4, 9, ..., 7, 2, 8]], dtype=object)

In [13]:
# حذف کردن سطر و ستونی که که دیتای پوچ دارند
data.dropna()

T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   .. ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 17 columns]

In [14]:
data.dropna(axis=1) # ما میتونیم ستون هایی که حداقل یک پوچ دارنذ را حذف کنیم

T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   .. ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 17 columns]

In [15]:
#آپشن های دیگر روش drop.na:
data.dropna(how='all')### حذف کردن رکوردهایی که تمام ویژگی پوچ هستند

T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   .. ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 17 columns]

In [4]:
# حذف کردن سطرهایی که حداقل 4 مقدار غیر پوچ دارند
data.dropna(thresh=4)

A  B    C    D
0  1  2  3.0  4.0

In [6]:
#only drop rows where NaN appear in specific columns (here: 'C', 'D')
data.dropna(subset=['C', 'D'])

A  B    C    D
0  1  2  3.0  4.0

In [10]:
#پر کردن مقادیر پوچ
from sklearn.preprocessing import Imputer
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)#Stategies:median(ordinal),most_frequent(nominal)
imr = imr.fit(data)
imputed_data = imr.transform(data.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [ 0. , 11. , 12. ,  6. ]])

In [31]:
#مدریت دیتای طبقه بندی شده
import pandas as pd
shahin = pd.DataFrame([
                  ['green', 'M', 10.1, 'class1'],
                  ['red', 'L', 13.5, 'class2'],
                  ['blue', 'XL', 15.3, 'class1']])
shahin.columns = ['color', 'size', 'price', 'classlabel']
shahin

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [32]:
#مپ کردن ویژگی های ترتیبی
# XL= L+1= M+2
size_mapping = {'XL': 3, 'L': 2, 'M': 1}
shahin['size'] = shahin['size'].map(size_mapping) 
shahin
                
               

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [13]:
# برگرداندن مقادیر مپ شده به حالت قبل
inv_size_mapping = {v: k for k, v in size_mapping.items()}
shahin['size'] = shahin['size'].map(inv_size_mapping) 
shahin

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [33]:
#Encoding class labels
import numpy as np
class_mapping = {label:idx for idx,label in enumerate(np.unique(shahin['classlabel']))}

class_mapping

{'class1': 0, 'class2': 1}

In [34]:
shahin['classlabel'] = shahin['classlabel'].map(class_mapping)
shahin

color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

In [35]:
# encoding on ویژگی های اسمی
from sklearn.preprocessing import LabelEncoder
X= shahin[['color', 'size', 'price']].values
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0])
X


array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [44]:
columns=['color', 'size', 'price']
X= pd.DataFrame(data=X, index=None, columns=columns)
X

color size price
0     1    1  10.1
1     2    2  13.5
2     0    3  15.3

In [45]:
Y=shahin['classlabel']
X= X.join(Y)
X



color size price  classlabel
0     1    1  10.1           0
1     2    2  13.5           1
2     0    3  15.3           0

In [25]:
#get dummies
shahin = pd.get_dummies(shahin[['price', 'color', 'size', 'classlabel']])
shahin

price  size  classlabel  color_blue  color_green  color_red
0   10.1     1           0           0            1          0
1   13.5     2           1           0            0          1
2   15.3     3           0           1            0          0

In [46]:
adult = pd.read_csv('C:\\Users\\ShahinN\\Desktop\\adult_income_data.txt')
adult.head(15)

age          workclass  fnlwgt      education  education-num  \
0    39          State-gov   77516      Bachelors             13   
1    50   Self-emp-not-inc   83311      Bachelors             13   
2    38            Private  215646        HS-grad              9   
3    53            Private  234721           11th              7   
4    28            Private  338409      Bachelors             13   
5    37            Private  284582        Masters             14   
6    49            Private  160187            9th              5   
7    52   Self-emp-not-inc  209642        HS-grad              9   
8    31            Private   45781        Masters             14   
9    42            Private  159449      Bachelors             13   
10   37            Private  280464   Some-college             10   
11   30          State-gov  141297      Bachelors             13   
12   23            Private  122272      Bachelors             13   
13   32            Private  205019     Assoc-acdm             12   
14   40            Private  121772      Assoc-voc             11   

            marital-status          occupation    relationship  \
0            Never-married        Adm-clerical   Not-in-family   
1       Married-civ-spouse     Exec-managerial         Husband   
2                 Divorced   Handlers-cleaners   Not-in-family   
3       Married-civ-spouse   Handlers-cleaners         Husband   
4       Married-civ-spouse      Prof-specialty            Wife   
5       Married-civ-spouse     Exec-managerial            Wife   
6    Married-spouse-absent       Other-service   Not-in-family   
7       Married-civ-spouse     Exec-managerial         Husband   
8            Never-married      Prof-specialty   Not-in-family   
9       Married-civ-spouse     Exec-managerial         Husband   
10      Married-civ-spouse     Exec-managerial         Husband   
11      Married-civ-spouse      Prof-specialty         Husband   
12           Never-married        Adm-clerical       Own-child   
13           Never-married               Sales   Not-in-family   
14      Married-civ-spouse        Craft-repair         Husband   

                   race      sex  capital-gain  capital-loss  hours-per-week  \
0                 White     Male          2174             0              40   
1                 White     Male             0             0              13   
2                 White     Male             0             0              40   
3                 Black     Male             0             0              40   
4                 Black   Female             0             0              40   
5                 White   Female             0             0              40   
6                 Black   Female             0             0              16   
7                 White     Male             0             0              45   
8                 White   Female         14084             0              50   
9                 White     Male          5178             0              40   
10                Black     Male             0             0              80   
11   Asian-Pac-Islander     Male             0             0              40   
12                White   Female             0             0              30   
13                Black     Male             0             0              50   
14   Asian-Pac-Islander     Male             0             0              40   

    native-country  income  
0    United-States   <=50K  
1    United-States   <=50K  
2    United-States   <=50K  
3    United-States   <=50K  
4             Cuba   <=50K  
5    United-States   <=50K  
6          Jamaica   <=50K  
7    United-States    >50K  
8    United-States    >50K  
9    United-States    >50K  
10   United-States    >50K  
11           India    >50K  
12   United-States   <=50K  
13   United-States   <=50K  
14               ?    >50K

In [59]:
adult.shape

(32561, 15)

In [47]:
print('education', np.unique(adult['education']))

education [' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']


In [55]:
adult['education']=np.where(adult['education'] == ' 10th', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' 11th', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' 12th', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' 1st-4th', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' 5th-6th', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' 7th-8th', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' 9th', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' HS-grad', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' Preschool', 'pre-university', adult['education'])
adult['education']=np.where(adult['education'] == ' Prof-school', 'pre-university', adult['education'])


In [57]:
adult['education'].unique()

array([' Bachelors', 'pre-university', ' Masters', ' Some-college',
       ' Assoc-acdm', ' Assoc-voc', ' Doctorate'], dtype=object)

In [58]:
adult.head(5)

age          workclass  fnlwgt       education  education-num  \
0   39          State-gov   77516       Bachelors             13   
1   50   Self-emp-not-inc   83311       Bachelors             13   
2   38            Private  215646  pre-university              9   
3   53            Private  234721  pre-university              7   
4   28            Private  338409       Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [64]:
class_mapping = {label:idx for idx,label in enumerate(np.unique(adult['income']))}

class_mapping

{' <=50K': 0, ' >50K': 1}

In [65]:
adult['income'] = adult['income'].map(class_mapping)

In [16]:
diabet =  pd.read_csv('C:\\ML\\dataset\\diabetes.csv')
diabet


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [17]:
X= diabet.values[:, 0:8]
y= diabet.values[:, 8]
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [19]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [ ]:
# نرمالسازی
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [20]:
X_train_norm

NameError: name 'X_train_norm' is not defined

In [21]:
# استاندارد سازی
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)


NameError: name 'X_train' is not defined

In [83]:
X_train_std

array([[-1.13311543,  0.9144385 ,  1.04559346, ...,  1.22646853,
        -0.3002719 , -1.05654479],
       [-0.8391623 , -1.19655127, -0.08570438, ..., -1.75097771,
         0.45699051, -0.55622332],
       [-0.54520916,  0.01416345,  0.01714088, ...,  0.56619802,
        -0.39305899, -0.55622332],
       ...,
       [ 0.0426971 , -0.85506763, -0.23997227, ..., -0.941212  ,
        -0.96774035, -1.05654479],
       [ 2.10036903, -1.13446334,  0.22283139, ..., -0.26848356,
        -0.51278428,  0.11087198],
       [ 0.33665024,  0.44877899,  0.63421243, ..., -4.01832171,
         0.50488062,  2.94602702]])