1. Transpose
2. Inverse
3. Trace
4. Determinant

In [1]:
# transpose
from numpy import array
# ساخت ماتریس
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# محاسبه 
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [3]:
# ماتریس معکوس
from numpy import array
from numpy.linalg import inv
# ساخت ماتریس
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# ساخت ماتریس معکوس
B = inv(A)
print(B)
# ضرب A و B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [4]:
# Trace

from numpy import array
from numpy import trace

A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [5]:
# دترمینان
# دترمینان ماتریس
from numpy import array
from numpy.linalg import det
# ساخت ماتریس
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# محاسبه دترمینان
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.66133814775094e-16
